# Specify the theme used for the Jekyll blog
theme: minima

# Title of the blog
title: Leap into the clouds

# Author of the blog
author: Rohit Kumar

# Short description of the blog
description: a blog to help you leap into the clouds
